apiVersion: v1
kind: Service
metadata:
  name: hello-world-message-json-go
  labels:
    app: hello-world-message-json-go
spec:
  ports:
  - port: 80
    targetPort: http
    name: http
    protocol: TCP
  type: NodePort
  selector:
    app: hello-world-message-json-go
