name: "Minikube workflow"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Minikube
      id: minikube
      uses: CodingNagger/minikube-setup-action@v1.0.2
    - name: Launch Minikube
      run: eval ${{ steps.minikube.outputs.launcher }}
    - name: Check pods
      run: |
        kubectl apply -f deployments/
        kubectl apply -f services/
        kubectl wait --for=condition=available --timeout=30s deployment/hello-world-message-json-go
        kubectl wait --for=condition=available --timeout=30s deployment/reverse-message-json-go
        curl $(minikube service hello-world-message-json-go --url)
        curl $(minikube service reverse-message-json-go --url)
